/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Вернуть состояние сервиса и его зависимостей.
         *
         *     Проверки подключены через `Depends`, чтобы тесты могли подменить их через
         *     `app.dependency_overrides` без реальных Postgres и Redis.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vacancies/recommended": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Recommended */
        get: operations["get_recommended_api_v1_vacancies_recommended_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vacancies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Vacancies */
        get: operations["list_vacancies_api_v1_vacancies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vacancies/filters/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Filters Meta */
        get: operations["get_filters_meta_api_v1_vacancies_filters_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vacancies/{vacancy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Vacancy */
        get: operations["get_vacancy_api_v1_vacancies__vacancy_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vacancies/{vacancy_id}/action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Action */
        post: operations["add_action_api_v1_vacancies__vacancy_id__action_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vacancies/{vacancy_id}/action/{action}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Action */
        delete: operations["remove_action_api_v1_vacancies__vacancy_id__action__action__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Resumes */
        get: operations["list_resumes_api_v1_resumes_get"];
        put?: never;
        /** Create Resume */
        post: operations["create_resume_api_v1_resumes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Resume
         * @description Черновик LLM сохраняется со статусом generated. Ошибки адаптера не ловятся.
         */
        post: operations["generate_resume_api_v1_resumes_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/{resume_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Resume */
        get: operations["get_resume_api_v1_resumes__resume_id__get"];
        put?: never;
        post?: never;
        /** Delete Resume */
        delete: operations["delete_resume_api_v1_resumes__resume_id__delete"];
        options?: never;
        head?: never;
        /** Update Resume */
        patch: operations["update_resume_api_v1_resumes__resume_id__patch"];
        trace?: never;
    };
    "/api/v1/resumes/{resume_id}/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Score Resume */
        post: operations["score_resume_api_v1_resumes__resume_id__score_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/{resume_id}/tailor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tailor Resume
         * @description Подстроить резюме под вакансию. Ошибки адаптера не ловятся.
         */
        post: operations["tailor_resume_api_v1_resumes__resume_id__tailor_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/{resume_id}/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Duplicate Resume */
        post: operations["duplicate_resume_api_v1_resumes__resume_id__duplicate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_api_v1_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_v1_sources_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{source_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enqueue Source Run
         * @description Поставить ручной обход. До Redis ничего не пишется и парсер не вызывается.
         */
        post: operations["enqueue_source_run_api_v1_sources__source_id__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CheckResult
         * @description Результат одной проверки зависимости.
         */
        CheckResult: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "error";
            /** Latency Ms */
            latency_ms?: number | null;
            /** Error */
            error?: string | null;
        };
        /**
         * EmploymentType
         * @description Тип занятости (раздел 3 ТЗ, поле `employment_type`).
         * @enum {string}
         */
        EmploymentType: "full_time" | "part_time" | "contract" | "internship" | "unknown";
        /**
         * ExperienceLevel
         * @description Грейд (раздел 3 ТЗ, поле `experience_level`).
         * @enum {string}
         */
        ExperienceLevel: "intern" | "junior" | "middle" | "senior" | "lead" | "unknown";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Сводный статус сервиса.
         */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Version */
            version: string;
            /** Checks */
            checks: {
                [key: string]: components["schemas"]["CheckResult"];
            };
        };
        /**
         * LanguageLevel
         * @description Уровень владения языком (раздел 4 ТЗ, `resume_languages.level`).
         * @enum {string}
         */
        LanguageLevel: "A1" | "A2" | "B1" | "B2" | "C1" | "C2" | "native";
        /**
         * MatchCriterionBreakdown
         * @description Разбивка по одному критерию матчинга (level / salary / location / freshness).
         */
        MatchCriterionBreakdown: {
            /** Points */
            points: number;
            /** Max Points */
            max_points: number;
            /** Reason */
            reason: string;
            /** Context */
            context?: {
                [key: string]: string | number | boolean | null;
            };
        };
        /**
         * MatchDetails
         * @description Разбивка score соответствия резюме и вакансии (заполняет `matching.py`).
         */
        MatchDetails: {
            skills: components["schemas"]["MatchSkillsBreakdown"];
            level: components["schemas"]["MatchCriterionBreakdown"];
            salary: components["schemas"]["MatchCriterionBreakdown"];
            location: components["schemas"]["MatchCriterionBreakdown"];
            freshness: components["schemas"]["MatchCriterionBreakdown"];
        };
        /**
         * MatchSkillsBreakdown
         * @description Разбивка по навыкам (до 45 баллов п. 5.6).
         */
        MatchSkillsBreakdown: {
            /** Matched */
            matched: string[];
            /** Missing */
            missing: string[];
            /** Points */
            points: number;
            /**
             * Max Points
             * @default 45
             */
            max_points: number;
            /** Reason */
            reason: string;
            /** Context */
            context?: {
                [key: string]: string | number | boolean | null;
            };
        };
        /** PaginatedResponse[VacancyListItem] */
        PaginatedResponse_VacancyListItem_: {
            /** Items */
            items: components["schemas"]["VacancyListItem"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /**
         * ParseQuality
         * @description Полнота разбора вакансии (раздел 3 ТЗ, поле `parse_quality`).
         * @enum {string}
         */
        ParseQuality: "full" | "partial";
        /**
         * ParseRunListResponse
         * @description Ответ GET /sources/runs: свежие запуски сверху.
         */
        ParseRunListResponse: {
            /** Items */
            items: components["schemas"]["ParseRunRead"][];
        };
        /**
         * ParseRunRead
         * @description Один запуск парсера (чтение из ORM ParseRun).
         */
        ParseRunRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            status: components["schemas"]["RunStatus"];
            /** Items Found */
            items_found: number;
            /** Items New */
            items_new: number;
            /** Error Text */
            error_text: string | null;
        };
        /**
         * RecommendedVacancyItem
         * @description Плоская карточка вакансии + score и match_details (не вложенный {vacancy: ...}).
         */
        RecommendedVacancyItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Company */
            company: string | null;
            /** City */
            city: string | null;
            /** Country */
            country: string | null;
            work_format: components["schemas"]["WorkFormat"];
            /** Salary Min */
            salary_min: number | null;
            /** Salary Max */
            salary_max: number | null;
            /** Salary Currency */
            salary_currency: string | null;
            salary_period: components["schemas"]["SalaryPeriod"] | null;
            /** Salary Is Gross */
            salary_is_gross: boolean | null;
            /** Skills */
            skills: string[];
            /** Published At */
            published_at: string | null;
            /** Source */
            source: string;
            /** Postings Count */
            postings_count: number;
            parse_quality: components["schemas"]["ParseQuality"];
            /** User Actions */
            user_actions?: components["schemas"]["UserAction"][];
            /** Score */
            score: number;
            match_details: components["schemas"]["MatchDetails"];
        };
        /**
         * RecommendedVacancyListResponse
         * @description Список рекомендаций без page / page_size.
         */
        RecommendedVacancyListResponse: {
            /** Resume Id */
            resume_id: string | null;
            /** Items */
            items: components["schemas"]["RecommendedVacancyItem"][];
        };
        /**
         * ResumeContacts
         * @description Контакты резюме: фиксированный набор ключей (зеркало JSONB contacts).
         */
        ResumeContacts: {
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Telegram */
            telegram?: string | null;
            /** Linkedin */
            linkedin?: string | null;
            /** Github */
            github?: string | null;
            /** Website */
            website?: string | null;
        };
        /**
         * ResumeCourseCreate
         * @description Курс или сертификат (вход).
         */
        ResumeCourseCreate: {
            /** Title */
            title: string;
            /** Provider */
            provider?: string | null;
            /** Year */
            year?: number | null;
            /** Certificate Url */
            certificate_url?: string | null;
        };
        /**
         * ResumeCourseRead
         * @description Курс или сертификат (чтение из ORM).
         */
        ResumeCourseRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Provider */
            provider: string | null;
            /** Year */
            year: number | null;
            /** Certificate Url */
            certificate_url: string | null;
        };
        /**
         * ResumeCreate
         * @description Создание резюме.
         *
         *     `user_id` приходит из зависимости `get_current_user_id`, `origin` ставит
         *     сервер; score / score_details на входе не принимаются.
         */
        ResumeCreate: {
            /** Title */
            title: string;
            /**
             * Is Primary
             * @default false
             */
            is_primary: boolean;
            /** Target Position */
            target_position?: string | null;
            /** Desired Salary Min */
            desired_salary_min?: number | null;
            /** Desired Salary Currency */
            desired_salary_currency?: string | null;
            /** Desired Country */
            desired_country?: string | null;
            /** Desired City */
            desired_city?: string | null;
            desired_work_format?: components["schemas"]["WorkFormat"] | null;
            /** Summary */
            summary?: string | null;
            contacts?: components["schemas"]["ResumeContacts"];
            /** Experience */
            experience?: components["schemas"]["ResumeExperienceCreate"][];
            /** Education */
            education?: components["schemas"]["ResumeEducationCreate"][];
            /** Skills */
            skills?: components["schemas"]["ResumeSkillCreate"][];
            /** Courses */
            courses?: components["schemas"]["ResumeCourseCreate"][];
            /** Languages */
            languages?: components["schemas"]["ResumeLanguageCreate"][];
        };
        /**
         * ResumeEducationCreate
         * @description Образование (вход).
         */
        ResumeEducationCreate: {
            /** Institution */
            institution: string;
            /** Degree */
            degree?: string | null;
            /** Field */
            field?: string | null;
            /** Start Year */
            start_year?: number | null;
            /** End Year */
            end_year?: number | null;
        };
        /**
         * ResumeEducationRead
         * @description Образование (чтение из ORM).
         */
        ResumeEducationRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Institution */
            institution: string;
            /** Degree */
            degree: string | null;
            /** Field */
            field: string | null;
            /** Start Year */
            start_year: number | null;
            /** End Year */
            end_year: number | null;
        };
        /**
         * ResumeExperienceCreate
         * @description Позиция в опыте работы (вход).
         */
        ResumeExperienceCreate: {
            /** Company */
            company: string;
            /** Position */
            position: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** End Date */
            end_date?: string | null;
            /**
             * Is Current
             * @default false
             */
            is_current: boolean;
            /** Description */
            description?: string | null;
            /** Achievements */
            achievements?: string | null;
        };
        /**
         * ResumeExperienceRead
         * @description Позиция в опыте работы (чтение из ORM).
         */
        ResumeExperienceRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Company */
            company: string;
            /** Position */
            position: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** End Date */
            end_date: string | null;
            /** Is Current */
            is_current: boolean;
            /** Description */
            description: string | null;
            /** Achievements */
            achievements: string | null;
        };
        /**
         * ResumeGenerateRequest
         * @description Тело POST /resumes/generate.
         */
        ResumeGenerateRequest: {
            /** Raw Text */
            raw_text: string;
            /** Target Position */
            target_position?: string | null;
        };
        /**
         * ResumeLanguageCreate
         * @description Владение языком (вход).
         */
        ResumeLanguageCreate: {
            /** Language */
            language: string;
            level: components["schemas"]["LanguageLevel"];
        };
        /**
         * ResumeLanguageRead
         * @description Владение языком (чтение из ORM).
         */
        ResumeLanguageRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Language */
            language: string;
            level: components["schemas"]["LanguageLevel"];
        };
        /**
         * ResumeListItem
         * @description Строка списка резюме пользователя (без секций).
         */
        ResumeListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Target Position */
            target_position: string | null;
            /** Is Primary */
            is_primary: boolean;
            origin: components["schemas"]["ResumeOrigin"];
            /** Score */
            score: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ResumeListResponse
         * @description Все резюме пользователя; без пагинации — их единицы.
         */
        ResumeListResponse: {
            /** Items */
            items: components["schemas"]["ResumeListItem"][];
        };
        /**
         * ResumeOrigin
         * @description Происхождение резюме: ручное, сгенерированное ИИ (п. 5.3) или копия (п. 5.2).
         * @enum {string}
         */
        ResumeOrigin: "manual" | "generated" | "duplicated";
        /**
         * ResumeRead
         * @description Полное резюме: колонки ORM + вложенные Read-секции.
         */
        ResumeRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Title */
            title: string;
            /** Is Primary */
            is_primary: boolean;
            origin: components["schemas"]["ResumeOrigin"];
            /** Target Position */
            target_position: string | null;
            /** Desired Salary Min */
            desired_salary_min: number | null;
            /** Desired Salary Currency */
            desired_salary_currency: string | null;
            /** Desired Country */
            desired_country: string | null;
            /** Desired City */
            desired_city: string | null;
            desired_work_format: components["schemas"]["WorkFormat"] | null;
            /** Summary */
            summary: string | null;
            contacts: components["schemas"]["ResumeContacts"];
            /** Score */
            score?: number | null;
            /** Score Details */
            score_details?: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Experience */
            experience?: components["schemas"]["ResumeExperienceRead"][];
            /** Education */
            education?: components["schemas"]["ResumeEducationRead"][];
            /** Skills */
            skills?: components["schemas"]["ResumeSkillRead"][];
            /** Courses */
            courses?: components["schemas"]["ResumeCourseRead"][];
            /** Languages */
            languages?: components["schemas"]["ResumeLanguageRead"][];
        };
        /**
         * ResumeScoreResponse
         * @description Ответ POST /resumes/{id}/score.
         */
        ResumeScoreResponse: {
            /** Score */
            score: number;
            /** Recommendations */
            recommendations: string[];
            /** Score Details */
            score_details: components["schemas"]["ScoreCriterionDetail"][];
        };
        /**
         * ResumeSkillCreate
         * @description Навык в резюме (вход) в любом написании.
         *
         *     К канону (`normalize_skills`: регистр, алиасы) навык приводит сервисный
         *     слой при записи, поэтому `Python` и `JS` здесь допустимы.
         */
        ResumeSkillCreate: {
            /** Skill */
            skill: string;
            /** Level */
            level?: number | null;
        };
        /**
         * ResumeSkillRead
         * @description Навык в резюме (чтение из ORM).
         */
        ResumeSkillRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Skill */
            skill: string;
            /** Level */
            level: number | null;
        };
        /**
         * ResumeTailorRequest
         * @description Тело POST /resumes/{id}/tailor.
         */
        ResumeTailorRequest: {
            /**
             * Vacancy Id
             * Format: uuid
             */
            vacancy_id: string;
        };
        /**
         * ResumeUpdate
         * @description Частичное обновление резюме.
         *
         *     Сервис вызывает `model_dump(exclude_unset=True)`: отсутствие поля
         *     в теле запроса ≠ null / пустой список; явный пустой список = очистка
         *     коллекции. Явный `null` допустим только у nullable-полей (очистка).
         */
        ResumeUpdate: {
            /** Title */
            title?: string | null;
            /** Is Primary */
            is_primary?: boolean | null;
            /** Target Position */
            target_position?: string | null;
            /** Desired Salary Min */
            desired_salary_min?: number | null;
            /** Desired Salary Currency */
            desired_salary_currency?: string | null;
            /** Desired Country */
            desired_country?: string | null;
            /** Desired City */
            desired_city?: string | null;
            desired_work_format?: components["schemas"]["WorkFormat"] | null;
            /** Summary */
            summary?: string | null;
            contacts?: components["schemas"]["ResumeContacts"] | null;
            /** Experience */
            experience?: components["schemas"]["ResumeExperienceCreate"][] | null;
            /** Education */
            education?: components["schemas"]["ResumeEducationCreate"][] | null;
            /** Skills */
            skills?: components["schemas"]["ResumeSkillCreate"][] | null;
            /** Courses */
            courses?: components["schemas"]["ResumeCourseCreate"][] | null;
            /** Languages */
            languages?: components["schemas"]["ResumeLanguageCreate"][] | null;
        };
        /**
         * RunStatus
         * @description Статус запуска парсера (раздел 4 ТЗ, `parse_runs.status`).
         * @enum {string}
         */
        RunStatus: "running" | "success" | "failed";
        /**
         * SalaryPeriod
         * @description Период, к которому отнесена зарплата (раздел 3 ТЗ, поле `salary_period`).
         * @enum {string}
         */
        SalaryPeriod: "month" | "year" | "hour";
        /**
         * ScoreCriterionDetail
         * @description Одна составляющая оценки резюме. Сумму весов 10.0 здесь не валидируем.
         */
        ScoreCriterionDetail: {
            key: components["schemas"]["ScoreCriterionKey"];
            /** Name */
            name: string;
            /** Weight */
            weight: number;
            /** Points */
            points: number;
            /** Issues */
            issues?: components["schemas"]["ScoreIssue"][];
            /** Recommendation */
            recommendation?: string | null;
        };
        /**
         * ScoreCriterionKey
         * @description Ключи критериев оценки резюме (п. 5.4 ТЗ).
         * @enum {string}
         */
        ScoreCriterionKey: "completeness" | "experience_quality" | "measurable_achievements" | "skills_relevance" | "chronology" | "education_courses" | "languages" | "goals_specificity";
        /**
         * ScoreIssue
         * @description Машиночитаемая проблема критерия: основа шаблонной (и будущей LLM) рекомендации.
         */
        ScoreIssue: {
            /** Code */
            code: string;
            /** Context */
            context?: {
                [key: string]: string | number | boolean;
            };
        };
        /**
         * SourceListItem
         * @description Источник в списке. Без config (секреты/селекторы наружу не отдаём).
         */
        SourceListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            source_type: components["schemas"]["SourceType"];
            /** Is Enabled */
            is_enabled: boolean;
            /** Location */
            location?: string | null;
            /** Last Run At */
            last_run_at: string | null;
            last_run_status: components["schemas"]["RunStatus"] | null;
            /** Last Error */
            last_error: string | null;
            /** Last Run Items Found */
            last_run_items_found?: number | null;
            /** Last Run Items New */
            last_run_items_new?: number | null;
        };
        /**
         * SourceListResponse
         * @description Ответ GET /sources.
         */
        SourceListResponse: {
            /** Items */
            items: components["schemas"]["SourceListItem"][];
        };
        /**
         * SourceRunAccepted
         * @description Ответ POST /sources/{id}/run: задача поставлена в очередь, обход ещё не начался.
         */
        SourceRunAccepted: {
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /** Job Id */
            job_id: string;
        };
        /**
         * SourceType
         * @description Тип источника вакансий (раздел 3 ТЗ, поле `source_type`).
         * @enum {string}
         */
        SourceType: "telegram" | "html" | "api";
        /**
         * UserAction
         * @description Действие пользователя над вакансией (п. 5.7 ТЗ).
         * @enum {string}
         */
        UserAction: "viewed" | "saved" | "hidden" | "applied";
        /**
         * VacancyActionRequest
         * @description Тело POST /vacancies/{id}/action (п. 5.7 ТЗ).
         */
        VacancyActionRequest: {
            action: components["schemas"]["UserAction"];
        };
        /**
         * VacancyDetailRead
         * @description Полная карточка: поля ленты + описание, требования и публикации.
         */
        VacancyDetailRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Company */
            company: string | null;
            /** City */
            city: string | null;
            /** Country */
            country: string | null;
            work_format: components["schemas"]["WorkFormat"];
            /** Salary Min */
            salary_min: number | null;
            /** Salary Max */
            salary_max: number | null;
            /** Salary Currency */
            salary_currency: string | null;
            salary_period: components["schemas"]["SalaryPeriod"] | null;
            /** Salary Is Gross */
            salary_is_gross: boolean | null;
            /** Skills */
            skills: string[];
            /** Published At */
            published_at: string | null;
            /** Source */
            source: string;
            /** Postings Count */
            postings_count: number;
            parse_quality: components["schemas"]["ParseQuality"];
            /** User Actions */
            user_actions?: components["schemas"]["UserAction"][];
            /** Description Clean */
            description_clean: string;
            /** Url */
            url: string | null;
            /** Relocation Support */
            relocation_support: boolean | null;
            /** Experience Min Years */
            experience_min_years: number | null;
            experience_level: components["schemas"]["ExperienceLevel"];
            employment_type: components["schemas"]["EmploymentType"];
            /** Education Required */
            education_required: string | null;
            /** Languages */
            languages: string[];
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            source_type: components["schemas"]["SourceType"];
            /** Is Active */
            is_active: boolean;
            /** Postings */
            postings?: components["schemas"]["VacancyPostingBriefRead"][];
            /** Match Score */
            match_score?: number | null;
            match_details?: components["schemas"]["MatchDetails"] | null;
        };
        /**
         * VacancyFiltersMeta
         * @description Доступные значения фильтров (GET /vacancies/filters/meta).
         */
        VacancyFiltersMeta: {
            /** Countries */
            countries: string[];
            /** Cities */
            cities: string[];
            /** Sources */
            sources: string[];
            /** Currencies */
            currencies: string[];
        };
        /**
         * VacancyListItem
         * @description Карточка ленты: все источники оффера и (при `resume_id`) балл соответствия.
         */
        VacancyListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Company */
            company: string | null;
            /** City */
            city: string | null;
            /** Country */
            country: string | null;
            work_format: components["schemas"]["WorkFormat"];
            /** Salary Min */
            salary_min: number | null;
            /** Salary Max */
            salary_max: number | null;
            /** Salary Currency */
            salary_currency: string | null;
            salary_period: components["schemas"]["SalaryPeriod"] | null;
            /** Salary Is Gross */
            salary_is_gross: boolean | null;
            /** Skills */
            skills: string[];
            /** Published At */
            published_at: string | null;
            /** Source */
            source: string;
            /** Postings Count */
            postings_count: number;
            parse_quality: components["schemas"]["ParseQuality"];
            /** User Actions */
            user_actions?: components["schemas"]["UserAction"][];
            /** Sources */
            sources?: string[];
            /** Match Score */
            match_score?: number | null;
            match_details?: components["schemas"]["MatchDetails"] | null;
        };
        /**
         * VacancyPostingBriefRead
         * @description Краткая публикация для блока «Источники» на карточке.
         */
        VacancyPostingBriefRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Source */
            source: string;
            source_type: components["schemas"]["SourceType"];
            /** Url */
            url: string | null;
            /** External Id */
            external_id: string;
            /** Published At */
            published_at: string | null;
            parse_quality: components["schemas"]["ParseQuality"];
        };
        /**
         * VacancySort
         * @description Сортировка ленты вакансий (п. 5.5 ТЗ). Живёт только в схемах, не в app.enums.
         * @enum {string}
         */
        VacancySort: "relevance" | "date" | "salary" | "match";
        /**
         * VacancyUserState
         * @description Текущее множество действий пользователя над вакансией (ответ на action).
         */
        VacancyUserState: {
            /**
             * Vacancy Id
             * Format: uuid
             */
            vacancy_id: string;
            /** Actions */
            actions: components["schemas"]["UserAction"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WorkFormat
         * @description Формат работы (раздел 3 ТЗ, поле `work_format`).
         * @enum {string}
         */
        WorkFormat: "remote" | "office" | "hybrid" | "unknown";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_recommended_api_v1_vacancies_recommended_get: {
        parameters: {
            query?: {
                resume_id?: string | null;
                exclude_hidden?: boolean;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendedVacancyListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_vacancies_api_v1_vacancies_get: {
        parameters: {
            query?: {
                q?: string | null;
                experience_level?: components["schemas"]["ExperienceLevel"][] | null;
                employment_type?: components["schemas"]["EmploymentType"][] | null;
                work_format?: components["schemas"]["WorkFormat"][] | null;
                country?: string | null;
                city?: string | null;
                salary_min?: number | null;
                salary_currency?: string | null;
                source?: string[] | null;
                published_after?: string | null;
                has_salary?: boolean | null;
                relocation_support?: boolean | null;
                exclude_hidden?: boolean;
                saved_only?: boolean;
                resume_id?: string | null;
                sort?: components["schemas"]["VacancySort"];
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_VacancyListItem_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_filters_meta_api_v1_vacancies_filters_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VacancyFiltersMeta"];
                };
            };
        };
    };
    get_vacancy_api_v1_vacancies__vacancy_id__get: {
        parameters: {
            query?: {
                resume_id?: string | null;
            };
            header?: never;
            path: {
                vacancy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VacancyDetailRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_action_api_v1_vacancies__vacancy_id__action_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vacancy_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VacancyActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VacancyUserState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_action_api_v1_vacancies__vacancy_id__action__action__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vacancy_id: string;
                action: components["schemas"]["UserAction"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VacancyUserState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_resumes_api_v1_resumes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeListResponse"];
                };
            };
        };
    };
    create_resume_api_v1_resumes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_resume_api_v1_resumes_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_resume_api_v1_resumes__resume_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_resume_api_v1_resumes__resume_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_resume_api_v1_resumes__resume_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    score_resume_api_v1_resumes__resume_id__score_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeScoreResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tailor_resume_api_v1_resumes__resume_id__tailor_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeTailorRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    duplicate_resume_api_v1_resumes__resume_id__duplicate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_api_v1_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceListResponse"];
                };
            };
        };
    };
    list_runs_api_v1_sources_runs_get: {
        parameters: {
            query?: {
                source_id?: string | null;
                status?: components["schemas"]["RunStatus"] | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParseRunListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enqueue_source_run_api_v1_sources__source_id__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceRunAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
