"""Публичный API пакета схем: реэкспорт основных классов."""

from app.schemas.ai import ResumeDraft, ResumeGenerateRequest, ResumeTailorRequest
from app.schemas.common import (
    ContentHashHex,
    CurrencyCode,
    ErrorDetail,
    ErrorResponse,
    PageNumber,
    PageSize,
    PaginatedResponse,
    VacancySort,
    validate_salary_range,
)
from app.schemas.normalized import NormalizedVacancy
from app.schemas.recommendations import (
    RecommendationsQuery,
    RecommendedVacancyItem,
    RecommendedVacancyListResponse,
)
from app.schemas.resumes import (
    ResumeContacts,
    ResumeCourseCreate,
    ResumeCourseRead,
    ResumeCreate,
    ResumeEducationCreate,
    ResumeEducationRead,
    ResumeExperienceCreate,
    ResumeExperienceRead,
    ResumeLanguageCreate,
    ResumeLanguageRead,
    ResumeRead,
    ResumeSkillCreate,
    ResumeSkillRead,
    ResumeUpdate,
)
from app.schemas.scoring import (
    MatchCriterionBreakdown,
    MatchDetails,
    MatchSkillsBreakdown,
    ResumeScoreResponse,
    ScoreCriterionDetail,
    ScoreCriterionKey,
)
from app.schemas.sources import ParseRunRead, SourceListItem
from app.schemas.vacancies import (
    VacancyActionRequest,
    VacancyCardRead,
    VacancyDetailRead,
    VacancyFiltersMeta,
    VacancyListQuery,
    VacancyListResponse,
    VacancyPostingBriefRead,
)

__all__ = [
    "ContentHashHex",
    "CurrencyCode",
    "ErrorDetail",
    "ErrorResponse",
    "MatchCriterionBreakdown",
    "MatchDetails",
    "MatchSkillsBreakdown",
    "NormalizedVacancy",
    "PageNumber",
    "PageSize",
    "PaginatedResponse",
    "ParseRunRead",
    "RecommendationsQuery",
    "RecommendedVacancyItem",
    "RecommendedVacancyListResponse",
    "ResumeContacts",
    "ResumeCourseCreate",
    "ResumeCourseRead",
    "ResumeCreate",
    "ResumeDraft",
    "ResumeEducationCreate",
    "ResumeEducationRead",
    "ResumeExperienceCreate",
    "ResumeExperienceRead",
    "ResumeGenerateRequest",
    "ResumeLanguageCreate",
    "ResumeLanguageRead",
    "ResumeRead",
    "ResumeScoreResponse",
    "ResumeSkillCreate",
    "ResumeSkillRead",
    "ResumeTailorRequest",
    "ResumeUpdate",
    "ScoreCriterionDetail",
    "ScoreCriterionKey",
    "SourceListItem",
    "VacancyActionRequest",
    "VacancyCardRead",
    "VacancyDetailRead",
    "VacancyFiltersMeta",
    "VacancyListQuery",
    "VacancyListResponse",
    "VacancyPostingBriefRead",
    "VacancySort",
    "validate_salary_range",
]
