"""initial schema

Revision ID: ba833660ecb2
Revises:
Create Date: 2026-09-19 23:03:40.498852

Тело ревизии получено `alembic revision --autogenerate` и вручную изменено в
двух местах, оба — читаемость, не семантика:

1. Порядок `create_table` переставлен на доменный (`sources` -> `vacancies` ->
   `vacancy_postings` -> `resumes` -> секции резюме -> `vacancy_matches` ->
   `user_vacancy_actions` -> `parse_runs`) вместо топологически-алфавитного,
   который выдаёт autogenerate. `downgrade` переставлен строго в обратном
   порядке.
2. Удалён дубль `from sqlalchemy.dialects import postgresql`: строка приходит
   из блока `${imports}` шаблона.

Ничего не дописано: CHECK от перечислений, GIN-индексы, генерируемая колонка
`search_vector`, частичный индекс `uq_resumes_primary_per_user` и все
`server_default` autogenerate отдал сам — см. отчёт этапа 2.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ba833660ecb2"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.Enum('telegram', 'html', 'api', name='source_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_status', sa.Enum('running', 'success', 'failed', name='last_run_status', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources')),
    sa.UniqueConstraint('slug', name=op.f('uq_sources_slug'))
    )
    op.create_table('vacancies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dedup_key', sa.String(length=64), nullable=True),
    sa.Column('dedup_key_raw', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('description_clean', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.Enum('telegram', 'html', 'api', name='source_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('work_format', sa.Enum('remote', 'office', 'hybrid', 'unknown', name='work_format', native_enum=False, create_constraint=True), server_default='unknown', nullable=False),
    sa.Column('relocation_support', sa.Boolean(), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sa.String(length=3), nullable=True),
    sa.Column('salary_period', sa.Enum('month', 'year', 'hour', name='salary_period', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('salary_is_gross', sa.Boolean(), nullable=True),
    sa.Column('skills', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('experience_min_years', sa.SmallInteger(), nullable=True),
    sa.Column('experience_level', sa.Enum('intern', 'junior', 'middle', 'senior', 'lead', 'unknown', name='experience_level', native_enum=False, create_constraint=True), server_default='unknown', nullable=False),
    sa.Column('employment_type', sa.Enum('full_time', 'part_time', 'contract', 'internship', 'unknown', name='employment_type', native_enum=False, create_constraint=True), server_default='unknown', nullable=False),
    sa.Column('education_required', sa.String(length=255), nullable=True),
    sa.Column('languages', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('parse_quality', sa.Enum('full', 'partial', name='parse_quality', native_enum=False, create_constraint=True), server_default='full', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('postings_count', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('russian', coalesce(title, '')), 'A') || setweight(to_tsvector('russian', coalesce(description_clean, '')), 'B') || setweight(to_tsvector('english', coalesce(title, '')), 'A') || setweight(to_tsvector('english', coalesce(description_clean, '')), 'B')", persisted=True), nullable=False),
    sa.CheckConstraint('(salary_min IS NULL OR salary_min >= 0) AND (salary_max IS NULL OR salary_max >= 0)', name=op.f('ck_vacancies_salary_non_negative')),
    sa.CheckConstraint('experience_min_years IS NULL OR experience_min_years BETWEEN 0 AND 60', name=op.f('ck_vacancies_experience_years_range')),
    sa.CheckConstraint('postings_count >= 1', name=op.f('ck_vacancies_postings_count_positive')),
    sa.CheckConstraint('salary_currency IS NULL OR salary_currency = upper(salary_currency)', name=op.f('ck_vacancies_currency_upper')),
    sa.CheckConstraint('salary_max IS NULL OR salary_min IS NULL OR salary_max >= salary_min', name=op.f('ck_vacancies_salary_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vacancies')),
    sa.UniqueConstraint('dedup_key', name=op.f('uq_vacancies_dedup_key'))
    )
    op.create_index(op.f('ix_vacancies_country_city'), 'vacancies', ['country', 'city'], unique=False)
    op.create_index(op.f('ix_vacancies_published_at'), 'vacancies', ['published_at'], unique=False)
    op.create_index(op.f('ix_vacancies_search_vector'), 'vacancies', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_vacancies_skills'), 'vacancies', ['skills'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_vacancies_source'), 'vacancies', ['source'], unique=False)
    op.create_table('vacancy_postings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vacancy_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.Enum('telegram', 'html', 'api', name='source_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('description_raw', sa.Text(), nullable=False),
    sa.Column('description_clean', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('parse_quality', sa.Enum('full', 'partial', name='parse_quality', native_enum=False, create_constraint=True), server_default='full', nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], name=op.f('fk_vacancy_postings_vacancy_id_vacancies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vacancy_postings')),
    sa.UniqueConstraint('source', 'content_hash', name=op.f('uq_vacancy_postings_source_content_hash')),
    sa.UniqueConstraint('source', 'external_id', name=op.f('uq_vacancy_postings_source_external_id'))
    )
    op.create_index(op.f('ix_vacancy_postings_vacancy_id_source'), 'vacancy_postings', ['vacancy_id', 'source'], unique=False)
    op.create_table('resumes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('origin', sa.Enum('manual', 'generated', 'duplicated', name='origin', native_enum=False, create_constraint=True), server_default='manual', nullable=False),
    sa.Column('target_position', sa.String(length=255), nullable=True),
    sa.Column('desired_salary_min', sa.Integer(), nullable=True),
    sa.Column('desired_salary_currency', sa.String(length=3), nullable=True),
    sa.Column('desired_country', sa.String(length=100), nullable=True),
    sa.Column('desired_city', sa.String(length=100), nullable=True),
    sa.Column('desired_work_format', sa.Enum('remote', 'office', 'hybrid', 'unknown', name='desired_work_format', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('contacts', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('score_details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('desired_salary_currency IS NULL OR desired_salary_currency = upper(desired_salary_currency)', name=op.f('ck_resumes_desired_currency_upper')),
    sa.CheckConstraint('desired_salary_min IS NULL OR desired_salary_min >= 0', name=op.f('ck_resumes_desired_salary_non_negative')),
    sa.CheckConstraint('score IS NULL OR score BETWEEN 0 AND 10', name=op.f('ck_resumes_score_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resumes'))
    )
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.create_index('uq_resumes_primary_per_user', 'resumes', ['user_id'], unique=True, postgresql_where=sa.text('is_primary'))
    op.create_table('resume_experience',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('resume_id', sa.Uuid(), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('position', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('achievements', sa.Text(), nullable=True),
    sa.CheckConstraint('NOT is_current OR end_date IS NULL', name=op.f('ck_resume_experience_current_has_no_end')),
    sa.CheckConstraint('end_date IS NULL OR end_date > start_date', name=op.f('ck_resume_experience_end_after_start')),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_resume_experience_resume_id_resumes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resume_experience'))
    )
    op.create_index(op.f('ix_resume_experience_resume_id_start_date'), 'resume_experience', ['resume_id', 'start_date'], unique=False)
    op.create_table('resume_education',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('resume_id', sa.Uuid(), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=False),
    sa.Column('degree', sa.String(length=255), nullable=True),
    sa.Column('field', sa.String(length=255), nullable=True),
    sa.Column('start_year', sa.SmallInteger(), nullable=True),
    sa.Column('end_year', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint('(start_year IS NULL OR start_year BETWEEN 1900 AND 2100) AND (end_year IS NULL OR end_year BETWEEN 1900 AND 2100)', name=op.f('ck_resume_education_year_range')),
    sa.CheckConstraint('start_year IS NULL OR end_year IS NULL OR end_year >= start_year', name=op.f('ck_resume_education_end_after_start')),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_resume_education_resume_id_resumes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resume_education'))
    )
    op.create_index(op.f('ix_resume_education_resume_id'), 'resume_education', ['resume_id'], unique=False)
    op.create_table('resume_skills',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('resume_id', sa.Uuid(), nullable=False),
    sa.Column('skill', sa.String(length=100), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint('level IS NULL OR level BETWEEN 1 AND 5', name=op.f('ck_resume_skills_level_range')),
    sa.CheckConstraint('skill = lower(skill)', name=op.f('ck_resume_skills_normalized')),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_resume_skills_resume_id_resumes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resume_skills')),
    sa.UniqueConstraint('resume_id', 'skill', name=op.f('uq_resume_skills_resume_id_skill'))
    )
    op.create_table('resume_courses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('resume_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=True),
    sa.Column('year', sa.SmallInteger(), nullable=True),
    sa.Column('certificate_url', sa.Text(), nullable=True),
    sa.CheckConstraint('year IS NULL OR year BETWEEN 1900 AND 2100', name=op.f('ck_resume_courses_year_range')),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_resume_courses_resume_id_resumes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resume_courses'))
    )
    op.create_index(op.f('ix_resume_courses_resume_id'), 'resume_courses', ['resume_id'], unique=False)
    op.create_table('resume_languages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('resume_id', sa.Uuid(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', 'native', name='level', native_enum=False, create_constraint=True), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_resume_languages_resume_id_resumes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resume_languages')),
    sa.UniqueConstraint('resume_id', 'language', name=op.f('uq_resume_languages_resume_id_language'))
    )
    op.create_table('vacancy_matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('resume_id', sa.Uuid(), nullable=False),
    sa.Column('vacancy_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('match_details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score BETWEEN 0 AND 100', name=op.f('ck_vacancy_matches_score_range')),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_vacancy_matches_resume_id_resumes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], name=op.f('fk_vacancy_matches_vacancy_id_vacancies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vacancy_matches')),
    sa.UniqueConstraint('resume_id', 'vacancy_id', name=op.f('uq_vacancy_matches_resume_id_vacancy_id'))
    )
    op.create_index(op.f('ix_vacancy_matches_resume_id_score'), 'vacancy_matches', ['resume_id', 'score'], unique=False)
    op.create_table('user_vacancy_actions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('vacancy_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Enum('viewed', 'saved', 'hidden', 'applied', name='action', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], name=op.f('fk_user_vacancy_actions_vacancy_id_vacancies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_vacancy_actions')),
    sa.UniqueConstraint('user_id', 'vacancy_id', 'action', name=op.f('uq_user_vacancy_actions_user_id_vacancy_id_action'))
    )
    op.create_index(op.f('ix_user_vacancy_actions_user_id_action'), 'user_vacancy_actions', ['user_id', 'action'], unique=False)
    op.create_table('parse_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('running', 'success', 'failed', name='status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('items_found', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('items_new', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.CheckConstraint('finished_at IS NULL OR finished_at >= started_at', name=op.f('ck_parse_runs_finished_after_started')),
    sa.CheckConstraint('items_found >= 0 AND items_new >= 0', name=op.f('ck_parse_runs_items_non_negative')),
    sa.CheckConstraint('items_new <= items_found', name=op.f('ck_parse_runs_items_new_within_found')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_parse_runs_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parse_runs'))
    )
    op.create_index(op.f('ix_parse_runs_source_id_started_at'), 'parse_runs', ['source_id', 'started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parse_runs_source_id_started_at'), table_name='parse_runs')
    op.drop_table('parse_runs')
    op.drop_index(op.f('ix_user_vacancy_actions_user_id_action'), table_name='user_vacancy_actions')
    op.drop_table('user_vacancy_actions')
    op.drop_index(op.f('ix_vacancy_matches_resume_id_score'), table_name='vacancy_matches')
    op.drop_table('vacancy_matches')
    op.drop_table('resume_languages')
    op.drop_index(op.f('ix_resume_courses_resume_id'), table_name='resume_courses')
    op.drop_table('resume_courses')
    op.drop_table('resume_skills')
    op.drop_index(op.f('ix_resume_education_resume_id'), table_name='resume_education')
    op.drop_table('resume_education')
    op.drop_index(op.f('ix_resume_experience_resume_id_start_date'), table_name='resume_experience')
    op.drop_table('resume_experience')
    op.drop_index('uq_resumes_primary_per_user', table_name='resumes', postgresql_where=sa.text('is_primary'))
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_vacancy_postings_vacancy_id_source'), table_name='vacancy_postings')
    op.drop_table('vacancy_postings')
    op.drop_index(op.f('ix_vacancies_source'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_skills'), table_name='vacancies', postgresql_using='gin')
    op.drop_index(op.f('ix_vacancies_search_vector'), table_name='vacancies', postgresql_using='gin')
    op.drop_index(op.f('ix_vacancies_published_at'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_country_city'), table_name='vacancies')
    op.drop_table('vacancies')
    op.drop_table('sources')
    # ### end Alembic commands ###
